# Generated by Django 5.0.2 on 2025-05-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_image',
            field=models.URLField(),
        ),
    ]
