# Generated by Django 5.0.2 on 2025-05-03 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_prescription_latitude_prescription_longitude'),
        ('users', '0002_pharmacyprofile_latitude_pharmacyprofile_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.pharmacyprofile'),
        ),
    ]
