# Generated by Django 5.0.2 on 2025-05-05 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_alter_prescription_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 5, 16, 18, 36, 398660, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
