# Generated by Django 5.0.2 on 2025-05-05 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_medicine_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
